### ISSUE TITLE
no installation instructions

### ISSUE THREAD

**Issue by ewheeler** [DhanushInfotech/opensrp-plugin#8]
no instructions for installing and running

no setup.py or pip requirements to know what dependencies are required

no instructions for running unit tests

**Comment by EswarSakamuri** [comment]
added requirements.txt and installation steps

**Comment by ewheeler** [comment]
@EswarSakamuri thanks, but i don't see any requirements.txt file

**Comment by EswarSakamuri** [comment]
Sorry Evan just now pushed the file

**Comment by ewheeler** [comment]
requirement.txt is missing some requirements, such as `django-smart-selects`
have you tested the provided installation instructions??

**Comment by ewheeler** [comment]
installation instructions also do not mention the need to update the settings.py file, which currently includes the IP address, username and password to a Dhanush database server

**Comment by harykeyrun** [comment]
We are not using django-smart-selects anymore and this library will be removed here after. Dhanush demo IPs will be replaced with dummy IPs/localhost. Instructions will be updated accordingly. And FYI  requirement.txt was tested on a local machine.

**Comment by ewheeler** [comment]
you are using `smart_selects`

it is in the settings in INSTALLED_APPS
https://github.com/DhanushInfotech/opensrp-plugin/blob/master/opensrp/settings.py#L40

and is imported in two locations:

https://github.com/DhanushInfotech/opensrp-plugin/blob/master/Masters/models.py#L9

https://github.com/DhanushInfotech/opensrp-plugin/blob/master/opensrp/urls.py#L44

the instructions do not work as written, so i would suggested testing again on a fresh machine

**Comment by EswarSakamuri** [comment]
Evan we tested requirement.txt but now found that we missed "python-dev" & "libpq-dev" need to be installed before executing requirement.txt. Updated installation steps.

WRT smart_selects we used it in earlier stages of project now we are not using that anymore so removed it completely.

**Comment by harykeyrun** [comment]
All the required instructions are given to install and or run tests
